### ISSUE TITLE
ScanCentral with -bt None removes files from GO payload

### ISSUE THREAD

**Issue by cripher** [fortify/gha-setup-scancentral-client#7]
Why does scan central remove files from the payload with -bt none? This makes this tool unusable in github actions etc. for payloads not using msbuild, maven, or gradle. Is this a known issue? Working as designed? 

Thank you

**Comment by rsenden** [comment]
This GitHub Action just sets up the ScanCentral Client; support for the actual ScanCentral components is provided through our regular support channels, or you can try asking this question on our community forum at https://community.microfocus.com/cyberres/fortify/.
